### ISSUE TITLE
To consider ESP32 support

### ISSUE THREAD

**Issue by baldram** [philipsen/IthoRadio#7]
Hello Wim,
I appreciate your work and thank you developing this interesting PlatformIO library.
I wonder whether it would work with ESP32? Have you considered this variant too?
Are there any plans to support this chip?

BR, Marcin

**Comment by philipsen** [comment]
I don't have an esp32, but i assume it would work fine.

**Comment by baldram** [comment]
Thanks for answer. There is a good chance it will work.
I don't have CC1101 to test it. I do research at the moment and probably I will be interested in such sub-1 GHz transceiver in the future. 
If in the meantime you'll have a chance to have fun with this great and powerful chip called ESP32, please leave some info then :) 

BR, Marcin

**Comment by philipsen** [comment]
will do
